---
- name: service restart
  hosts: all
  become: true
  tasks:
  - name: Restart service apache2, in all cases
    service:
     name: apache2
     state: restarted
  - name: enable the service
    service:
      name: apache2
      enabled: yes
